In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
%matplotlib inline

In [9]:
plt.xlabel('Area(sqr feet)')
plt.ylabel('Price(USD)')
plt.scatter(df.area,df.price,marker='+',color='red')

In [14]:
reg=linear_model.LinearRegression()
_area = df.area.values.reshape(-1,1)
_price = df.price.values.reshape(-1,1)

In [16]:
reg.fit(_area,_price)
# training the model using the available data points -- fitting the data

LinearRegression()

In [17]:
reg.predict([[3300]]) # individually giving the area

array([[628715.75342466]])

In [13]:
# drawing the linear line
plt.xlabel('Area(sqr feet)')
plt.ylabel('Price(USD)')
plt.scatter(df.area,df.price,marker='+',color='red')
plt.plot(df.area,reg.predict(df[['area']]),color='blue')

In [18]:
reg.coef_

array([[135.78767123]])

In [19]:
reg.intercept_

array([180616.43835616])

In [20]:
#y=mx+c
135.78767123 *3300 +180616.43835616

628715.75341516

### Given a CSV values as input

In [21]:
d=pd.read_csv('areas.csv')
d.head()

area
0  1000
1  1500
2  2300
3  3540
4  4120

In [23]:
predicted_price=reg.predict(d)
predicted_price

array([[ 316404.10958904],
       [ 384297.94520548],
       [ 492928.08219178],
       [ 661304.79452055],
       [ 740061.64383562],
       [ 799808.21917808],
       [ 926090.75342466],
       [ 650441.78082192],
       [ 825607.87671233],
       [ 492928.08219178],
       [1402705.47945205],
       [1348390.4109589 ],
       [1144708.90410959]])

In [24]:
d['prices']=predicted_price

In [25]:
d.head()

area         prices
0  1000  316404.109589
1  1500  384297.945205
2  2300  492928.082192
3  3540  661304.794521
4  4120  740061.643836

In [26]:
d.to_csv("prediction.csv",index=None)

# Finding Canada's percapita income

In [27]:
df=pd.read_csv('canada_per_capita_income.csv')
df.head()

year       income
0  1970  3399.299037
1  1971  3768.297935
2  1972  4251.175484
3  1973  4804.463248
4  1974  5576.514583

In [28]:
reg=linear_model.LinearRegression()

In [29]:
_year = df.year.values.reshape(-1,1)
_income = df.income.values.reshape(-1,1)

In [30]:
reg.fit(_year,_income)

LinearRegression()

In [31]:
reg.predict([[2020]]) # predicting the percapita income for the year 2020

array([[41288.69409442]])

In [32]:
reg.predict([[2022]])

array([[42945.62424486]])

In [33]:
reg.predict([[2040]])

array([[57857.99559887]])