In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digit=load_digits()

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Train Test Split

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test=train_test_split(digit.data,digit.target,test_size=0.2)

In [6]:
len(x_test)

360

In [7]:
len(x_train)

1437

# Logistic Regression

In [9]:
reg=LogisticRegression()

In [10]:
reg.fit(x_train,y_train)

C:\Users\kcjc608\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [11]:
reg.score(x_test,y_test)

0.9444444444444444

# SVM

In [12]:
svm=SVC()

In [13]:
svm.fit(x_train,y_train)

SVC()

In [14]:
svm.score(x_test,y_test)

0.9888888888888889

# Random Forest

In [15]:
rf=RandomForestClassifier()

In [16]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [17]:
rf.score(x_test,y_test)

0.975

In [ ]:
# Train test split method changes the train and test sample everytime we executing. 
# And then we need to execute the classifier again and again.

# Defining functions to calculate the score

In [21]:
def calculate_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [22]:
calculate_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\kcjc608\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9444444444444444

In [24]:
calculate_score(SVC(),x_train,x_test,y_train,y_test)

0.9888888888888889

In [25]:
calculate_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9722222222222222

# K Fold Cross validation

In [18]:
from sklearn.model_selection import KFold

In [19]:
kf=KFold(n_splits=3)

In [26]:
for train_index,test_index in kf.split([10,11,12,20,21,22,30,31,32]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# Stratified K Fold

In [29]:
from sklearn.model_selection import StratifiedKFold

In [30]:
folds=StratifiedKFold(n_splits=3)

In [33]:
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [34]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [48]:
score_l=[]
score_svm=[]
score_random=[]
for train_index,test_index in kf.split(digit.data):
    x_train, x_test, y_train, y_test = digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    score_l.append(calculate_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svm.append(calculate_score(SVC(),x_train,x_test,y_train,y_test))
    score_random.append(calculate_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))


C:\Users\kcjc608\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kcjc608\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

In [44]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [45]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [46]:
score_random

[0.9482470784641068, 0.9549248747913188, 0.9398998330550918]

# Cross Val score - with different Algorithms

In [49]:
from sklearn.model_selection import cross_val_score

In [50]:
cross_val_score(LogisticRegression(),digit.data,digit.target)

C:\Users\kcjc608\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kcjc608\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_i

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [51]:
cross_val_score(SVC(),digit.data,digit.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [52]:
cross_val_score(RandomForestClassifier(),digit.data,digit.target)

array([0.93888889, 0.89722222, 0.9637883 , 0.9637883 , 0.92479109])

# Cross validation - With same Algorithm and different parameter - Parameter Tuning

In [54]:
cross_val_score(RandomForestClassifier(n_estimators=15),digit.data,digit.target)

array([0.89166667, 0.86944444, 0.93871866, 0.9637883 , 0.88857939])

In [55]:
cross_val_score(RandomForestClassifier(n_estimators=50),digit.data,digit.target)

array([0.93611111, 0.91388889, 0.95543175, 0.96935933, 0.90250696])

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=35),digit.data,digit.target)

array([0.93333333, 0.87222222, 0.95543175, 0.96657382, 0.9275766 ])