In [1]:
from sklearn.datasets import load_iris
iris=load_iris()

In [2]:
import pandas as pd

In [3]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [9]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [10]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
df['flower']=iris.target

In [6]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
df['flower']=df.flower.map({
    0:'setosa',
    1:'versicolor',
    2:'virginica'
})

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

# Method 1 :Train Test split

In [14]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test=train_test_split(iris.data,iris.target,test_size=0.2)

# Model

In [39]:
from sklearn import svm

In [42]:
model=SVC(kernel='rbf',C=30,gamma='auto')

In [21]:
model.fit(x_train,y_train)

SVC(C=30, gamma='auto')

In [23]:
model.score(x_test,y_test)

1.0

In [24]:
# scores are changing... So Iam going for K fold cross validation approach

#  Method 2 :K Fold cross validation

In [25]:
from sklearn.model_selection import cross_val_score

In [40]:
from sklearn.svm import SVC

In [41]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [43]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [44]:
cross_val_score(SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [45]:
import numpy as np

In [52]:
kernels=['rbf','linear']
C=[1,10,20]
average_scores={}
for k in kernels:
    for c in C:
        cv_scores=cross_val_score(SVC(kernel=k,C=c,gamma='auto'),iris.data,iris.target,cv=5)
        average_scores[k+str(c)]=np.average(cv_scores)
average_scores

{'rbf1': 0.9800000000000001,
 'rbf10': 0.9800000000000001,
 'rbf20': 0.9666666666666668,
 'linear1': 0.9800000000000001,
 'linear10': 0.9733333333333334,
 'linear20': 0.9666666666666666}

# Method 3 : GridSearch CV


In [53]:
from sklearn.model_selection import GridSearchCV

In [58]:
clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [59]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [61]:
clf.cv_results_

{'mean_fit_time': array([0.00117121, 0.00119982, 0.00100017, 0.00099998, 0.00140195,
        0.00099988]),
 'std_fit_time': array([2.33818918e-04, 4.01450124e-04, 3.37174788e-07, 5.91739352e-07,
        4.88680377e-04, 3.50402318e-07]),
 'mean_score_time': array([0.00052691, 0.00079961, 0.00099974, 0.00020008, 0.00059891,
        0.00080009]),
 'std_score_time': array([4.51316055e-04, 3.99806628e-04, 1.21943587e-06, 4.00161743e-04,
        4.89009211e-04, 4.00042886e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'ker

In [62]:
df=pd.DataFrame(clf.cv_results_)

In [63]:
df.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001171  2.338189e-04         0.000527        0.000451       1   
1       0.001200  4.014501e-04         0.000800        0.000400       1   
2       0.001000  3.371748e-07         0.001000        0.000001      10   
3       0.001000  5.917394e-07         0.000200        0.000400      10   
4       0.001402  4.886804e-04         0.000599        0.000489      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5

In [64]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [65]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits

In [66]:
clf.best_score_

0.9800000000000001

In [67]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [68]:
 # limitations : we can have multiple parameters, 
# so computational cost will go high. Becuase in turn it finds the permutaiton and combination for each of the features

# Method 4 : RandomizedSearchCV

In [69]:
from sklearn.model_selection import RandomizedSearchCV

In [73]:
rs=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},
cv=5,
return_train_score=False,
n_iter=2
)

In [74]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [76]:
rs.cv_results_

{'mean_fit_time': array([0.00139952, 0.00139947]),
 'std_fit_time': array([0.00079954, 0.00049119]),
 'mean_score_time': array([0.00060029, 0.0004003 ]),
 'std_score_time': array([0.00049014, 0.00049027]),
 'param_kernel': masked_array(data=['rbf', 'linear'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 1],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 1}, {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1.]),
 'mean_test_score': array([0.98, 0.98]),
 'std_test_score': array([0.01632993, 0.01632993]),
 'rank_test_score': array([1, 1])}

In [77]:
df=pd.DataFrame(rs.cv_results_)

In [78]:
df.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.001400      0.000800           0.0006         0.00049          rbf   
1       0.001399      0.000491           0.0004         0.00049       linear   

  param_C                        params  split0_test_score  split1_test_score  \
0       1     {'kernel': 'rbf', 'C': 1}           0.966667                1.0   
1       1  {'kernel': 'linear', 'C': 1}           0.966667                1.0   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.966667           0.966667                1.0             0.98   
1           0.966667           0.966667                1.0             0.98   

   std_test_score  rank_test_score  
0         0.01633                1  
1         0.01633                1

In [79]:
df[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0          rbf       1             0.98
1       linear       1             0.98

# Chossing Best Model

In [80]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [1]:
model_params={
    'svm':{
        'model':SVC(),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
        
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
        
    },
    'logistic_regression':{
        'model':LogisticRegression(),
        'params':{
            'C':[1,5,10]
        }
        
    }
}

NameError: name 'SVC' is not defined