# Predicting Home price based on 3 variables

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('homepricess.csv')

In [3]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
median=df.bedrooms.median()
median

4.0

In [5]:
df.bedrooms.fillna(median,inplace=True)

In [6]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [9]:
reg.coef_ #m1, m2, m3 are coefficents

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

221323.0018654043

In [11]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [12]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [30]:
reg.predict([[2500,4,5]])

array([578876.03748933])

# Exercise

In [13]:
df=pd.read_csv('hiring.csv')

In [14]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [15]:
df.experience=df.experience.fillna("Zero")

In [16]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [17]:
pip install word2number


Note: you may need to restart the kernel to use updated packages.


In [18]:
from word2number import w2n

In [19]:
df.experience=df.experience.apply(w2n.word_to_num)

In [20]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [21]:
df.isnull().sum().sort_values(ascending=False)

test_score(out of 10)         1
experience                    0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [22]:
mean_val=df['test_score(out of 10)'].mean()

In [23]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(mean_val)

In [24]:
df.isnull().sum().sort_values(ascending=False)

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [25]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [26]:
reg.predict([[2,9,6]])

array([53290.89255945])

In [70]:
reg.predict([[12,10,10]])

array([92268.07227784])