In [1]:
import pandas as pd
import numpy as np

In [35]:
df=pd.read_csv('homepricesss.csv')

In [36]:
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [37]:
df.isnull().sum()

town     0
area     0
price    0
dtype: int64

In [38]:
df=pd.get_dummies(df,drop_first=True)

In [39]:
df.head()

area   price  town_robinsville  town_west windsor
0  2600  550000                 0                  0
1  3000  565000                 0                  0
2  3200  610000                 0                  0
3  3600  680000                 0                  0
4  4000  725000                 0                  0

In [29]:
from sklearn import linear_model

In [30]:
reg=linear_model.LinearRegression()

In [43]:
x=df.drop('price',axis=1)
x

area  town_robinsville  town_west windsor
0   2600                 0                  0
1   3000                 0                  0
2   3200                 0                  0
3   3600                 0                  0
4   4000                 0                  0
5   2600                 0                  1
6   2800                 0                  1
7   3300                 0                  1
8   3600                 0                  1
9   2600                 1                  0
10  2900                 1                  0
11  3100                 1                  0
12  3600                 1                  0

In [46]:
y=df.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [47]:
reg.fit(x,y)

LinearRegression()

In [49]:
reg.predict([[2800,0,1]])

array([605103.20361213])

In [50]:
reg.predict([[2800,1,0]])

array([590775.63964739])

In [51]:
reg.predict([[2800,0,0]])

array([565089.22812298])

In [52]:
reg.score(x,y) 95 % accurate

0.9573929037221871

# Label Encoder

In [79]:
df=pd.read_csv('homepricesss.csv')
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [80]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [81]:
dfle=df


In [82]:
dfle.town=le.fit_transform(dfle.town)

In [83]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [84]:
x=df[['town','area']].values # 2 dimensional array instead of data frame
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [85]:
y=dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [86]:
reg.fit(x,y)

LinearRegression()

In [87]:
reg.predict([[1,2800]])

array([587143.58452138])

In [100]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [101]:
x=ohe.fit_transform(x).toarray()
x

array([[1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        0., 1., 1., 0., 1., 0.],
       [1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 1., 1., 0.],
       [0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,

In [102]:
x=x[:,1:]
x

array([[0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1.,
        0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 0., 1., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
        1., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 0., 1., 1., 0.],
       [1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
        0., 1., 0.,

In [103]:
ohe.fit(x,y)

OneHotEncoder()

In [105]:
ohe.predict([[1,0,2800]])

AttributeError: 'OneHotEncoder' object has no attribute 'predict'

# Exercise

In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [108]:
df=pd.read_csv('carprices.csv')
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [109]:
df.isnull().sum()

Car Model        0
Mileage          0
Sell Price($)    0
Age(yrs)         0
dtype: int64

In [112]:
df=pd.get_dummies(df,drop_first=True)
df

Mileage  Sell Price($)  Age(yrs)  Car Model_BMW X5  \
0     69000          18000         6                 1   
1     35000          34000         3                 1   
2     57000          26100         5                 1   
3     22500          40000         2                 1   
4     46000          31500         4                 1   
5     59000          29400         5                 0   
6     52000          32000         5                 0   
7     72000          19300         6                 0   
8     91000          12000         8                 0   
9     67000          22000         6                 0   
10    83000          20000         7                 0   
11    79000          21000         7                 0   
12    59000          33000         5                 0   

    Car Model_Mercedez Benz C class  
0                                 0  
1                                 0  
2                                 0  
3                                 0  
4                                 0  
5                                 0  
6                                 0  
7                                 0  
8                                 0  
9                                 1  
10                                1  
11                                1  
12                                1

In [113]:
from sklearn import linear_model

In [116]:
x=df.drop('Sell Price($)',axis=1)
x

Mileage  Age(yrs)  Car Model_BMW X5  Car Model_Mercedez Benz C class
0     69000         6                 1                                0
1     35000         3                 1                                0
2     57000         5                 1                                0
3     22500         2                 1                                0
4     46000         4                 1                                0
5     59000         5                 0                                0
6     52000         5                 0                                0
7     72000         6                 0                                0
8     91000         8                 0                                0
9     67000         6                 0                                1
10    83000         7                 0                                1
11    79000         7                 0                                1
12    59000         5                 0                                1

In [117]:
y=df['Sell Price($)']
y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [118]:
reg=linear_model.LinearRegression()

In [119]:
reg.fit(x,y)

LinearRegression()

In [120]:
reg.predict([[45000,4,0,1]])

array([36991.31721061])

In [121]:
reg.predict([[86000,7,1,0]])

array([11080.74313219])

In [122]:
reg.score(x,y)

0.9417050937281083